plugins:
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Layout/HashAlignment:
  EnforcedColonStyle: table
Layout/IndentationWidth:
  Width: 2
Layout/LineLength:
  Max: 120
Layout/TrailingWhitespace:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Enabled: true
Lint/ConstantDefinitionInBlock:
  Enabled: true
Lint/NonDeterministicRequireOrder:
  Enabled: true
Lint/RedundantCopDisableDirective:
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Lint/UselessAssignment:
  Enabled: true

Style/Alias:
  Enabled: true
Style/BlockDelimiters:
  EnforcedStyle: line_count_based
Style/Documentation:
  Enabled: true
Style/FetchEnvVar:
  Enabled: true
Style/GlobalVars:
  Enabled: true
Style/GuardClause:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/MethodCallWithArgsParentheses:
  EnforcedStyle: omit_parentheses
  AllowParenthesesInChaining: true
  AllowParenthesesInMultilineCall: true
  AllowParenthesesInCamelCaseMethod: true
Style/NumericPredicate:
  Enabled: true
Style/NegatedIf:
  Enabled: true
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
